import Head from "next/head";
import { api } from "@/utils/api";
import type { Product } from "@prisma/client";
import { ProductCard } from "@/components/Product";

export default function Home() {
  const { data: products, isLoading } = api.product.getAllProduct.useQuery();

  if (isLoading) {
    return <div>Cargando...</div>;
  }

  return (
    <>
      <Head>
        <title>Tazas Store by Typerian</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="flex min-h-[90vh] flex-grow flex-col">
          <div className="flex flex-col space-x-4 space-y-4 px-4">
            <h3 className="mt-3 text-2xl font-semibold">
              Productos destacados
            </h3>

            {products?.length ? (
              <ul className="mt-4 grid gap-5 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4">
                {products?.map((product: Product) => (
                  <ProductCard {...{ product }} key={product.id} />
                ))}
              </ul>
            ) : (
              <div className="flex justify-center p-4">
                No hay productos disponibles, vuelve mas tarde!
              </div>
            )}
          </div>
        </main>
      </div>
    </>
  );
}
